### ISSUE TITLE
Save Record in cloudkit

### ISSUE THREAD

**Issue by slice-mohit** [jacksonjude/cloudkit_flutter#8]
Hey @jacksonjude, how can we save a record in cloudkit using this package. The example app only uses fetch operation and I couldn't find this in readme as well. Please let me know how can I save data in cloudkit using this package.

**Comment by MrUnfunny** [comment]
I think the 'records/modify' calls are not yet implemented. So, does this package not support creating/modifying records?

**Comment by jacksonjude** [comment]
Hey @slice-mohit! In the released 0.1 version of the package, modifying records is not yet supported. However in version 0.2, which is still in development on the 0.2 branch, record modification is one of many new features.

If you would like to use version 0.2 in your own project, simply include the following in your `pubspec.yaml` file:
```yaml
dependencies:
  flutter:
    sdk: flutter

  cloudkit_flutter:
    git:
      url: https://github.com/jacksonjude/cloudkit_flutter.git
      ref: 0.2
```
